
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShortcutActivationSetting(activation: ShortcutActivation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_shortcut_activation_setting", { activation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeHoldThresholdMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_hold_threshold_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayAfterMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_after_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeReliablePasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_reliable_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister all bindings while the user is recording a
 * shortcut in the UI. This avoids firing actions while keys are recorded.
 */
async suspendAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register all bindings after the user has finished recording.
 */
async resumeAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadBackendSetting(backend: VadBackend) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_backend_setting", { backend }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFillerWordRemovalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_filler_word_removal_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowWhatsNewOnUpdateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhatsNewLastSeenVersionSetting(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureInputStatus() : Promise<SecureInputStatus> {
    return await TAURI_INVOKE("get_secure_input_status");
},
async runKeyboardDiagnostic(durationSecs: number | null) : Promise<Result<KeyboardDiagnosticReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_keyboard_diagnostic", { durationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async isUpdateChecksLocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_update_checks_locked");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCloudCredential(label: string, providerId: string, secret: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_cloud_credential", { label, providerId, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a credential in place.
 * 
 * A `None` secret leaves the stored key untouched, so the UI can save a label
 * or provider change without ever round-tripping the secret through the
 * frontend.
 */
async updateCloudCredential(id: string, label: string | null, providerId: string | null, secret: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_cloud_credential", { id, label, providerId, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCloudCredential(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cloud_credential", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify a credential, and return the models it can reach.
 * 
 * One command rather than two: listing models and proving the key works are
 * the same `GET /models` call, and splitting them meant the model picker could
 * learn a key was rejected and then not say so. On several providers this
 * succeeds for a key with no chat or audio scope, so it proves authentication,
 * not capability.
 */
async testCloudCredential(id: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_cloud_credential", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCloudBinding(capability: Capability, binding: CapabilityBinding) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cloud_binding", { capability, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCloudCredentialStatus(capability: Capability) : Promise<Result<CredentialCapabilityStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cloud_credential_status", { capability }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lift a cooldown by hand, so a just-fixed key does not need hours or a
 * restart to prove it works.
 */
async clearCloudCooldown(capability: Capability, credentialId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_cloud_cooldown", { capability, credentialId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async getMicrophoneChannels(deviceName: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_channels", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedChannel(channel: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_channel", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stub implementation for non-macOS platforms
 * Always returns false since laptop detection is macOS-specific
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
cloudDegradedEvent: CloudDegradedEvent,
historyUpdatePayload: HistoryUpdatePayload,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
cloudDegradedEvent: "cloud-degraded-event",
historyUpdatePayload: "history-update-payload",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The container-level `serde(default)` (backed by the `Default` impl below)
 * guarantees every field — including ones added in the future — falls back to
 * its `get_default_settings()` value when missing from a stored settings
 * object, so a partial store can never fail the whole load (#1619).
 * Field-level defaults below take precedence where present.
 */
export type AppSettings = { 
/**
 * Internal settings schema marker for one-time migrations. Fresh installs
 * start at the current version; existing stores missing this key are
 * treated as version 0 and migrated forward.
 */
settings_schema_version?: number; 
/**
 * Defaults to empty on partial stores; the load path merges in the
 * default bindings for any missing keys before the settings are used.
 */
bindings?: Partial<{ [key in string]: ShortcutBinding }>; 
/**
 * Replaces the pre-0.10 `push_to_talk` bool; stores missing this key are
 * migrated from it in `apply_settings_migrations`.
 */
shortcut_activation?: ShortcutActivation; 
/**
 * Hold-or-toggle only: a press held at least this long is push-to-talk,
 * anything shorter is a tap that locks recording on.
 */
hold_threshold_ms?: number; audio_feedback?: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; show_whats_new_on_update?: boolean; 
/**
 * The app version whose What's New the user has already seen. Fresh installs
 * default to the current version (nothing is "new" to them). Existing users
 * upgrading from before this key existed are blanked by the migration so they
 * see the current release's notes — see `apply_settings_migrations`.
 */
whats_new_last_seen_version?: string; selected_model?: string; onboarding_completed?: boolean; always_on_microphone?: boolean; selected_microphone?: string | null; 
/**
 * Which input channel to use on the selected microphone device.
 * None means "average all channels" (original behavior).
 */
selected_channel?: number | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; 
/**
 * Fork: one entry per API key, stored once however many capabilities use it.
 */
cloud_credentials?: Credential[]; 
/**
 * Fork: secrets keyed by `Credential::id`. Kept in settings alongside
 * upstream's `post_process_api_keys` rather than an OS credential store, a
 * recorded trade to avoid a keyring dependency. Revisit before wider
 * distribution.
 */
cloud_credential_secrets?: SecretMap; 
/**
 * Fork: per-capability configuration, both disabled by default.
 */
cloud_bindings?: CapabilityBindings; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; theme?: Theme; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; paste_delay_after_ms?: number; 
/**
 * Debug-gated ("beta") receipt-sequenced paste: restore the clipboard only
 * after the target app actually reads the transcript, instead of after a
 * fixed delay. See `paste_tx`. macOS and Windows only.
 */
reliable_paste?: boolean; typing_tool?: TypingTool; external_script_path?: string | null; filler_word_removal_enabled?: boolean; custom_filler_words?: string[] | null; transcribe_accelerator?: TranscribeAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; 
/**
 * Stable transcribe.cpp device selector. This is derived from the backend's
 * `device_id` when available (or its name for backends such as Metal),
 * never from the process-local device registry index.
 */
transcribe_gpu_device?: string | null; extra_recording_buffer_ms?: number; vad_enabled?: boolean; 
/**
 * Experimental detector implementation. Silero remains the stable default.
 */
vad_backend?: VadBackend; 
/**
 * Which recording overlay to show: None / Minimal / Live. Streaming mode is
 * not gated on this — that follows model capability. Migrated from the old
 * `overlay_position` (position `none` → style `None`).
 */
overlay_style?: OverlayStyle }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type Capability = "stt" | "post_process"
export type CapabilityBinding = { 
/**
 * Speech only. Post-processing has no switch of its own: upstream's
 * `post_process_enabled` is the on/off, and an empty rotation is what says
 * "use upstream's single key instead of the pool".
 */
enabled?: boolean; 
/**
 * Order is the round-robin sequence. A credential may appear more than
 * once so long as each appearance names a different model: providers meter
 * per model, so those are independent quotas. Same key and same model is
 * rejected, which is what keeps the "tried once per request" budget honest.
 */
entries?: RotationEntry[]; 
/**
 * Speech only: vocabulary bias, shared by every entry. Cleanup
 * instructions are per entry instead, via [`RotationEntry::prompt_id`].
 */
prompt?: string; policy?: RotationPolicy; cooldown_secs?: number; strike_threshold?: number; strike_window_secs?: number; 
/**
 * On for speech means "run the local model" when every key is
 * unavailable; off means the failure surfaces instead.
 */
fallback_enabled?: boolean; 
/**
 * Speech only. Empty means auto-detect.
 */
language?: string }
export type CapabilityBindings = { stt?: CapabilityBinding; post_process?: CapabilityBinding }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CloudDegradeOutcome = "fell_back_to_local" | "raw_transcript" | 
/**
 * Nothing ran and the dictation was lost.
 */
"failed"
/**
 * Translatable cause. One variant per thing a user could act on, rather than
 * one per call site: "add a key" and "your keys are failing" need different
 * answers, everything else is the same shrug.
 */
export type CloudDegradeReason = 
/**
 * Nothing usable in the rotation: none selected, none with a model set, or
 * none whose provider serves this.
 */
"not_configured" | 
/**
 * Every credential was tried and every one failed.
 */
"all_credentials_failed" | 
/**
 * The recording is larger than the upload limit.
 */
"recording_too_large" | 
/**
 * The rotation ran past its time budget.
 */
"timed_out" | "unexpected"
/**
 * Emitted whenever output quality dropped. Silent degradation is worse than
 * failure: the user would blame the model instead of an exhausted key.
 */
export type CloudDegradedEvent = { capability: string; outcome: CloudDegradeOutcome; 
/**
 * What the UI shows, once translated. The backend cannot produce user-
 * facing prose: it has no locale, and the project's rule is that every
 * visible string comes from i18next.
 */
reason: CloudDegradeReason; 
/**
 * Diagnostic detail for `handy.log` only, never rendered. Log-safe; never
 * contains a key.
 */
detail: string }
/**
 * The secret is not here: it lives in `AppSettings::cloud_credential_secrets`
 * keyed by [`Credential::id`], so this can be logged and rendered freely.
 */
export type Credential = { 
/**
 * Bindings reference this, never the label, so renaming cannot detach a
 * credential from its rotation state.
 */
id: string; label: string; provider_id: string; validity?: CredentialValidity }
/**
 * Not merged into the credentials list: a key can cool down for chat while
 * serving speech, so a single badge would be a lie.
 */
export type CredentialCapabilityStatus = { credential_id: string; 
/**
 * Identifies the rotation entry alongside `credential_id`: quotas are
 * metered per model, so the same key has separate state per model.
 */
model: string; capability: string; 
/**
 * Seconds of cooldown left, or 0 when the credential is available.
 */
cooldown_remaining_secs: number; recent_strikes: number; last_used_ms: number | null; 
/**
 * A revoked key is skipped on every request but has no cooldown and no
 * strikes, so without this it would read as healthy here.
 */
validity: CredentialValidity }
/**
 * Key-level health, as shown in the credentials list.
 * 
 * Not per-capability: a key can cool down for chat while serving speech, so a
 * single badge would be a lie. Per-capability health lives in the capability
 * tabs.
 */
export type CredentialValidity = "untested" | "valid" | 
/**
 * The provider answered 401/403.
 */
"invalid"
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
export type GpuDeviceOption = { id: string; name: string; total_vram_mb: number }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardDiagnosticReport = { secure_input_enabled: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Counts only — key identity is deliberately never captured.
 */
key_down: number; key_up: number; flags_changed: number; mouse: number; duration_ms: number }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Handy obtains it — the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk — a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display. `Minimal` and `Live` share one base
 * (the pill); `Live` grows into the panel that shows live transcription text.
 * `None` hides the overlay entirely. Decoupled from whether the model runs in
 * streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean; 
/**
 * Extended in place rather than as a fork-owned parallel type, which would
 * conflict every time upstream touches provider handling.
 */
capabilities?: Capability[]; 
/**
 * `None` means no speech endpoint, regardless of what `capabilities` says.
 */
stt_endpoint?: string | null; 
/**
 * Speech-to-English. Separate because it is a different endpoint, not a
 * parameter: `translate_to_english` is an upstream setting the local engine
 * honours, so cloud speech has to honour it too.
 */
stt_translate_endpoint?: string | null; 
/**
 * False for Apple Intelligence and a Custom entry pointed at local Ollama.
 */
requires_credential?: boolean }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
/**
 * One participant in a rotation.
 * 
 * The model lives here rather than on the binding because two providers never
 * share a model id: an OpenAI key and a Groq key in one rotation need
 * different ones, and a single shared value would fail every request on
 * whichever provider does not own it.
 */
export type RotationEntry = { credential_id: string; 
/**
 * For Apple Intelligence this is a token limit, matching upstream.
 */
model?: string; 
/**
 * Post-processing only. References `AppSettings::post_process_prompts`.
 * `None` falls back to the binding's default template.
 */
prompt_id?: string | null }
/**
 * How the pool picks among credentials already known to be eligible.
 * Policies never see ineligible ones: filtering happens first, in one place.
 */
export type RotationPolicy = "round_robin" | 
/**
 * Oldest last-used first. Matches round robin in steady state but
 * self-corrects after restarts, cooldown expiry, or a key added
 * mid-session, where a raw cursor would point somewhere stale.
 */
"least_recently_used"
/**
 * `pub`, not `pub(crate)`: it is reachable through `pub` fields of
 * `AppSettings`, so the narrower visibility only produced a warning.
 */
export type SecretMap = Partial<{ [key in string]: string }>
export type SecureInputStatus = { 
/**
 * Secure input is currently enabled (live check)
 */
enabled: boolean; 
/**
 * Enabled continuously long enough to be considered stuck (not just a
 * password field gaining momentary focus)
 */
sustained: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Carbon fallback registrations are currently active
 */
fallback_active: boolean; 
/**
 * Binding ids shadow-registered with identical semantics
 */
covered_bindings: string[]; 
/**
 * Side-specific binding ids widened to match either side while shadowed
 */
degraded_bindings: string[]; 
/**
 * Binding ids that cannot fire at all (e.g. fn+key, registration failure)
 */
uncovered_bindings: string[]; 
/**
 * The user tried to record a shortcut while secure input was active.
 * Treated as user impact even when every binding is covered, so the
 * warning banner appears and explains why recording refused.
 */
recorder_blocked: boolean }
/**
 * How the transcribe shortcut's key events drive a recording.
 */
export type ShortcutActivation = 
/**
 * Press to start, press again to stop.
 */
"toggle" | 
/**
 * Hold to record, release to stop.
 */
"push_to_talk" | 
/**
 * Hold to record and release to stop, or tap to keep recording until the
 * next press. Which one it was is decided by how long the key was held
 * (`hold_threshold_ms`).
 */
"hold_or_toggle"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing — show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
/**
 * UI appearance mode. `System` follows the OS `prefers-color-scheme`; `Light`
 * and `Dark` force one of the two palettes Handy already ships.
 */
export type Theme = "system" | "light" | "dark"
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type VadBackend = "silero" | "earshot"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
